api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cart-transform-donation"
type = "function"
uid = "166b0831-214b-1df6-28b0-d3a18d4888b2dcd4e93a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
