api_version = "2026-01"

[[extensions]]
uid = "32cad21c-a827-3644-1247-6442d3c6ae6603b626d6"
type = "ui_extension"
name = "Donation"
handle = "checkout-donation-upsell"

  [[extensions.targeting]]
  target = "purchase.checkout.block.render"
  module = "./src/Checkout.jsx"

  [extensions.capabilities]
  api_access = true

  [extensions.settings]

    [[extensions.settings.fields]]
    key = "product_handle"
    type = "single_line_text_field"
    name = "Donation product handle"
    description = "The handle of the donation product (e.g. 'donate')"

    [[extensions.settings.fields]]
    key = "heading"
    type = "single_line_text_field"
    name = "Heading"
    description = "Widget heading text"

    [[extensions.settings.fields]]
    key = "description"
    type = "single_line_text_field"
    name = "Description"
    description = "Widget description text"
